jobs:
- job: Windows_x64
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    submodules: true
    persistCredentials: true
  - template: "windows-steps.yml"
    parameters:
      architecture: "x64"
      compilerPath: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/Llvm/x64/bin/clang-cl.exe"
      vcpkgTriplet: "x64-windows-static"
      vcvarsPath: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
- job: Windows_x86
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    submodules: true
    persistCredentials: true
  - template: "windows-steps.yml"
    parameters:
      architecture: "x86"
      compilerPath: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/Llvm/bin/clang-cl.exe"
      vcpkgTriplet: "x86-windows-static"
      vcvarsPath: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars32.bat"
